# Import library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns

# 한글이 깨지는 문제
font_name = fm.FontProperties(fname="C:\\Windows\\Fonts\\malgun.ttf").get_name()
plt.rc("font", family=font_name)

# 한글 적용 후 기호가 미출력
import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"] = False

import urllib.request as req
from urllib.request import urlopen
from urllib.error import HTTPError, URLError
import urllib.parse
from bs4 import BeautifulSoup
import requests

# Load Data

In [3]:
raw_data = pd.read_excel("C:\\RWork\\data\\hn20_all(spss)\\hn20_all(spss)\\hn20_all.xlsx")

In [5]:
raw_data.head()

,mod_d,ID,ID_fam,year,region,town_t,apt_t,psu,sex,age,...,LF_S10,LF_S11,LF_S12,LF_S13,LF_S14,LF_S14_1,LF_S15,LF_S16,LF_SECUR,LF_SECUR_G
0,2022.02.28.,A801169401,A8011694,2020.0,1.0,1.0,2.0,A801,1.0,39.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
1,2022.02.28.,A801169402,A8011694,2020.0,1.0,1.0,2.0,A801,2.0,39.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
2,2022.02.28.,A801169403,A8011694,2020.0,1.0,1.0,2.0,A801,1.0,10.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
3,2022.02.28.,A801169404,A8011694,2020.0,1.0,1.0,2.0,A801,1.0,7.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
4,2022.02.28.,A801169405,A8011694,2020.0,1.0,1.0,2.0,A801,1.0,4.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0

In [7]:
select_data = raw_data['ID', 'ID_fam', 'region', 'town_t', 'apt_t', 'sex', 'age', 'age_month', 'incm', 'ho_incm', 'incm5', 'ho_incm5', 
                      'edu', 'occp', 'cfam', 'genertn', 'allownc', 'house', 'live_t', 'ainc', 'marri_1', 'marri_2', 'fam_rela', 'tins',
                      'npins', 'ID_F', 'ID_M', 'D_1_1', 'D_2_1', 'D_2_wk', 'DI1_pr', 'DI1_2', 'DI2_pr', 'DI2_2', 'DI3_pr', 'DI3_2',
                       'DI4_pr', 'DI5_pr', 'DI6_pr', 'DM1_pr', 'DM2_pr', 'DM3_pr', 'DM4_pr', 'DJ2_pr', 'DJ4_pr', 'DE2_pr', 'DE1_pr', 
                       '', ''
                      ]